# Generated by Django 4.0.5 on 2022-06-10 07:57

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connector', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Location')),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Address')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.IntegerField(default=161, verbose_name='Port')),
                ('channel_1', models.BooleanField(default=False, verbose_name='Channel 1')),
                ('channel_2', models.BooleanField(default=False, verbose_name='Channel 2')),
                ('channel_3', models.BooleanField(default=False, verbose_name='Channel 3')),
                ('channel_4', models.BooleanField(default=False, verbose_name='Channel 4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='connector.device', verbose_name='Device')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'Location List',
                'db_table': 'location',
            },
        ),
    ]
