# Generated by Django 4.0.5 on 2022-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status_1',
            field=models.IntegerField(default=-1, verbose_name='Status 1'),
        ),
        migrations.AddField(
            model_name='location',
            name='status_2',
            field=models.IntegerField(default=-1, verbose_name='Status 2'),
        ),
        migrations.AddField(
            model_name='location',
            name='status_3',
            field=models.IntegerField(default=-1, verbose_name='Status 3'),
        ),
        migrations.AddField(
            model_name='location',
            name='status_4',
            field=models.IntegerField(default=-1, verbose_name='Status 4'),
        ),
    ]
