# Generated by Django 4.0.5 on 2022-06-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_status_1_location_status_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='channel_1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='channel_2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='channel_3',
        ),
        migrations.RemoveField(
            model_name='location',
            name='channel_4',
        ),
        migrations.AddField(
            model_name='location',
            name='parameter_1',
            field=models.BooleanField(default=False, verbose_name='Parameter 1'),
        ),
        migrations.AddField(
            model_name='location',
            name='parameter_2',
            field=models.BooleanField(default=False, verbose_name='Parameter 2'),
        ),
        migrations.AddField(
            model_name='location',
            name='parameter_3',
            field=models.BooleanField(default=False, verbose_name='Parameter 3'),
        ),
        migrations.AddField(
            model_name='location',
            name='parameter_4',
            field=models.BooleanField(default=False, verbose_name='Parameter 4'),
        ),
    ]
