# Generated by Django 4.0.5 on 2022-06-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_ping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='device_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Device Type'),
        ),
    ]
