# Generated by Django 4.0.5 on 2022-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_location_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notification_1',
            field=models.BooleanField(default=False, verbose_name='Notification Camera 1'),
        ),
        migrations.AddField(
            model_name='location',
            name='notification_2',
            field=models.BooleanField(default=False, verbose_name='Notification Camera 2'),
        ),
        migrations.AddField(
            model_name='location',
            name='notification_3',
            field=models.BooleanField(default=False, verbose_name='Notification Camera 3'),
        ),
        migrations.AddField(
            model_name='location',
            name='notification_4',
            field=models.BooleanField(default=False, verbose_name='Notification Camera 4'),
        ),
    ]
