# Generated by Django 4.0.5 on 2022-06-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='map_center',
            field=models.CharField(default='-1.233982000061532, 116.83728437200422', max_length=100, verbose_name='Map Center'),
        ),
        migrations.AddField(
            model_name='region',
            name='map_zoom',
            field=models.IntegerField(default=9, verbose_name='Map Zoom'),
        ),
    ]
