# Generated by Django 4.0.5 on 2022-06-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_region_map_center_region_map_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='map_zoom',
            field=models.FloatField(default=9, verbose_name='Map Zoom'),
        ),
    ]
