# Generated by Django 4.0.5 on 2022-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'device', 'verbose_name_plural': 'device List'},
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Device Brand'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(max_length=30, unique=True, verbose_name='Device Type'),
        ),
    ]
