# Generated by Django 4.0.5 on 2022-06-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_alter_device_options_alter_device_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='parameter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parameter_type', to='connector.parameter', verbose_name='Parameter Device Type'),
        ),
    ]
