# Generated by Django 4.0.5 on 2022-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_device_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connector',
            field=models.CharField(choices=[('SNMP', 'SNMP'), ('HTTP', 'HTTP')], default='SNMP', max_length=20, verbose_name='Connector Type'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='connector',
            field=models.CharField(choices=[('SNMP', 'SNMP'), ('HTTP', 'HTTP')], default='SNMP', max_length=20, verbose_name='Connector Type'),
        ),
    ]
